# Generated by Django 3.1.6 on 2021-02-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='sur_name',
            new_name='second_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='tg_name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='language_code',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
