# Generated by Django 3.1.6 on 2021-03-02 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210224_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordset',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
    ]
