# Generated by Django 3.1.6 on 2021-03-02 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210302_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordset',
            name='student',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='core.student'),
            preserve_default=False,
        ),
    ]
